print(5+7)
print(7-5)
print(5*7)
print(10/5)
a = 5
b = 10 
print(f"The adddition of these numbers is: {a+b}")
print(f"The subtraction of these numbers is: {a-b}")
print(f"The multiplication of these numbers is: {a*b}")
print(f"The divison of these numbers is: {a/b}")
c = int(input("Type minutes you want in hour: "))
print("The hour of your minutes is ",c//60)
d = int(input("Type hour you want in minutes: "))
print("The minutes of your hour is ",60*d)
e = int(input("Type the number of rupees you have: "))
print(f"You have {e//48} dollars")
f = int(input("Type the number of dollar you have: "))
print(f"You have {f*48} rupees")
g = int(input("Enter the amount in dollars: "))
print(f"You have {(g*48)//70} pounds")
h = int(input("Type number of grams: "))
print(f"You have {h/1000} kg")
i = int(input("Type number of kilograms: "))
print(f"You have {1000*i} kg")
j = int(input("Enter the number of bytes: "))
print(f"You have {j/1000} kb")
print(f"You have {j/1000000} mb")
print(f"You have {j/1000000000} gb")
k = int(input("Enter the Celcius: "))
print(f"You have {((9/5) * k) + 32} farenhits")
l = int(input("Enter the farenhit: "))
print(f"You have {5/9*(l-32)}celcius")
m = int(input("Enter the principle amount: "))
r = int(input("Enter the rate of interest: "))
n = int(input("Enter number of years: "))
print(f"Your interest is {m*r*n/100}")
o = int(input("Enter the length of the square: "))
print(f"The area of the square is {o**2} and it's perimeter is {4*o}")
p = int(input("Enter the radius of the circle: "))
print(f"The area of the circle is {3.14*(p**2)}")
q = int(input("Enter the height of the triangle: "))
s = int(input("Enter the base of the triangle: "))
print(f"The area of the triangle is {(q*s)/2}")
t = (int(input("Enter Your Salary: ")))
print(f"Your allowance from the salary is : {t*0.1}")
print(f"Your deduction from the salary is : {t*0.03}")
print(f"Your net salary is {t + (t*0.1) - (t*0.03)}")
u = 93
v = 90
w = 91
print(f"Total marks: {u +v+ w}")
print(f"Average Marks are: {(u+v+w)/3}")
x = 20
y = 30
x,y = y,x
print("x = ", x)
print("y = ", y)
